COMMENTS_FILE_PATH = 'data/comments.txt'
CONFIG_FILE_PATH = 'config/config.json'
FOLLOWERS_FILE_PATH = 'data/followers.csv'
FOLLOWING_FILE_PATH = 'data/following.csv'
HASHTAGS_FILE_PATH = 'data/hashtags.txt'
NOT_FOLLOWING_FILE_PATH = 'data/not_following.csv'

COMMENT = 'comment'
FALSE = 'false'
FOLLOW = 'follow'
HASHTAG = 'hashtag'
LIKE = 'like'
PASSWORD = 'password'
TRUE = 'true'
UNFOLLOW = 'unfollow'
USERNAME = 'username'

A = 'a'
ARIA_LABEL = 'aria-label'
EMPTY = ''
HREF = 'href'
PREFS = 'prefs'
PROFILE_MANAGED_IMAGES = 'profile.managed_default_content_settings.images'
R = 'r'
SLASH_P = '/p/'
UTF8 = 'utf8'
W = 'w'
YPFFH = 'Ypffh'

SCROLL_DOWN = 'window.scrollTo(0, -document.body.scrollHeight);'
SCROLL_UP = 'window.scrollTo(0, document.body.scrollHeight);'

ANALYZE_NON_FOLLOWER = 'analyze_non_follower'
DISABLE_IMAGE = 'disable_image'
HEADLESS = 'headless'
LIKES_PER_HASHTAG = 'likes_per_hashtag'

INSTAGRAM_HOME_URL = 'https://www.instagram.com/'
EXPLORE_URL = INSTAGRAM_HOME_URL + 'explore/'
TAGS_URL = INSTAGRAM_HOME_URL + 'explore/tags/'

CHECK_LIKE_XPATH = "//button[normalize-space(@class)='wpO6b']/div[normalize-space(@class)='QBdPU']/span/*[name()='svg']"
FOLLOW_BUTTON_XPATH = '//*[@id="react-root"]/section/main/div/div[1]/article/header/div[2]/div[1]/div[2]/button'
LIKE_BUTTON_XPATH = '//*[@id="react-root"]/section/main/div/div[1]/article/div[3]/section[1]/span[1]/button'
LOGIN_ERROR_XPATH = '//*[@id="slfErrorAlert"]'
POST_COMMENT_BUTTON_XPATH = '//button[contains(text(), "Post")]'
UNFOLLOW_BUTTON_OPENER_XPATH = '//*[@id="react-root"]/section/main/div/header/section/div[1]/div[1]/div/div[2]/div/span/span[1]/button'
UNFOLLOW_BUTTON_XPATH = '/html/body/div[4]/div/div/div/div[3]/button[1]'

DEFAULT_LIKES_PER_HASHTAG = '15'
EMPTY_PASSWORD = 'Empty Password!'
EMPTY_USERNAME = 'Empty Username!'
INITIALIZING = 'Initializing ... '
NO_FILE_FOUND = 'No file found'
PAGE_NOT_FOUND = 'Page Not Found • Instagram'
INVALID_CREDENTIALS = 'Sorry, your password was incorrect. Please double-check your password.'
LOGIN_SUCCESS = 'Login Success ...'
WDM_LOG_LEVEL = 'WDM_LOG_LEVEL'
